### ISSUE TITLE
Build failed 

### ISSUE THREAD

**Issue by thanhdiepts** [mkschreder/jucid#9]
orange_ws_server.c: In function '_find_interface_from_ip':
orange_ws_server.c:340:9: error: cast increases required alignment of target type [-Werror=cast-align]
    sa = (struct sockaddr_in _)(iap->ifa_addr);
         ^
cc1: all warnings being treated as errors
Makefile:579: recipe for target 'liborange_la-orange_ws_server.lo' failed
make[5]: *_\* [liborange_la-orange_ws_server.lo] Error 1
make[5]: Leaving directory '/build/dir/xxx/build_dir/target-mips_24kc_musl-1.1.15/orange-rpcd-2.16.08-be81ae8caf3caa9d846331f3548c9116b716bca4/src'
Makefile:391: recipe for target 'all-recursive' failed
make[4]: **\* [all-recursive] Error 1
make[4]: Leaving directory '/build/dir/xxx/build_dir/target-mips_24kc_musl-1.1.15/orange-rpcd-2.16.08-be81ae8caf3caa9d846331f3548c9116b716bca4'
Makefile:65: recipe for target '/build/dir/xxx/build_dir/target-mips_24kc_musl-1.1.15/orange-rpcd-2.16.08-be81ae8caf3caa9d846331f3548c9116b716bca4/.built' failed
make[3]: **\* [/build/dir/xxx/build_dir/target-mips_24kc_musl-1.1.15/orange-rpcd-2.16.08-be81ae8caf3caa9d846331f3548c9116b716bca4/.built] Error 2
make[3]: Leaving directory '/build/dir/xxx/feeds/juci/orange-rpcd'
package/Makefile:124: recipe for target 'package/feeds/juci/orange-rpcd/compile' failed
make[2]: **\* [package/feeds/juci/orange-rpcd/compile] Error 2
make[2]: Leaving directory '/build/dir/xxx'
package/Makefile:121: recipe for target '/build/dir/xxx/staging_dir/target-mips_24kc_musl-1.1.15/stamp/.package_compile' failed
make[1]: **\* [/build/dir/xxx/staging_dir/target-mips_24kc_musl-1.1.15/stamp/.package_compile] Error 2
make[1]: Leaving directory '/build/dir/xxx'
/build/dir/xxx/include/toplevel.mk:193: recipe for target 'world' failed
make: **\* [world] Error 2

**Comment by mkschreder** [comment]
Very good that it got caught. I have rewritten that part now to use getnameinfo instead and it should fix your error I think (you need to double check!). I have just pushed it into this repo and not yet into the juci-openwrt-feed. You can update your openwrt package to point to this commit id and try building again: 

```
aade61983c31296d22dbce039cce0d42de1a1386
```
